Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
filename = "figures/pmf_plot_poisson_mu20_bulk.pdf"

hs = np.arange(0, 40)
fHs = rvH.pmf(hs)

# mask all non-bulk
fHs[0:int(I_95[0])] = np.nan
fHs[int(I_95[1])+1:] = np.nan


fig, ax = plt.subplots()
ax.stem(fHs, label="Bulk of the pmf $f_H$", basefmt=" ")
ax.set_xlabel('h')
ax.set_ylabel('$f_H$')
ax.set_ylim([0, 0.1])
ax.legend()
# plt.title()
plt.xticks(hs)
ax.figure.tight_layout()
ax.figure.savefig(filename, dpi=300, bbox_inches="tight", pad_inches=0)

rvH.cdf(I_95[1]) - rvH.cdf(I_95[0])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [39][0m, in [0;36m<cell line: 20>[0;34m()[0m
[1;32m     18[0m plt[38;5;241m.[39mxticks(hs)
[1;32m     19[0m ax[38;5;241m.[39mfigure[38;5;241m.[39mtight_layout()
[0;32m---> 20[0m [43max[49m[38;5;241;43m.[39;49m[43mfigure[49m[38;5;241;43m.[39;49m[43msavefig[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mdpi[49m[38;5;241;43m=[39;49m[38;5;241;43m300[39;49m[43m,[49m[43m [49m[43mbbox_inches[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mtight[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mpad_inches[49m[38;5;241;43m=[39;49m[38;5;241;43m0[39;49m[43m)[49m
[1;32m     22[0m rvH[38;5;241m.[39mcdf(I_95[[38;5;241m1[39m]) [38;5;241m-[39m rvH[38;5;241m.[39mcdf(I_95[[38;5;241m0[39m])

File [0;32m/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/matplotlib/figure.py:3046[0m, in [0;36mFigure.savefig[0;34m(self, fname, transparent, **kwargs)[0m
[1;32m   3042[0m     [38;5;28;01mfor[39;00m ax [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39maxes:
[1;32m   3043[0m         stack[38;5;241m.[39menter_context(
[1;32m   3044[0m             ax[38;5;241m.[39mpatch[38;5;241m.[39m_cm_set(facecolor[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnone[39m[38;5;124m'[39m, edgecolor[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnone[39m[38;5;124m'[39m))
[0;32m-> 3046[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcanvas[49m[38;5;241;43m.[39;49m[43mprint_figure[49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/matplotlib/backend_bases.py:2319[0m, in [0;36mFigureCanvasBase.print_figure[0;34m(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)[0m
[1;32m   2315[0m [38;5;28;01mtry[39;00m:
[1;32m   2316[0m     [38;5;66;03m# _get_renderer may change the figure dpi (as vector formats[39;00m
[1;32m   2317[0m     [38;5;66;03m# force the figure dpi to 72), so we need to set it again here.[39;00m
[1;32m   2318[0m     [38;5;28;01mwith[39;00m cbook[38;5;241m.[39m_setattr_cm([38;5;28mself[39m[38;5;241m.[39mfigure, dpi[38;5;241m=[39mdpi):
[0;32m-> 2319[0m         result [38;5;241m=[39m [43mprint_method[49m[43m([49m
[1;32m   2320[0m [43m            [49m[43mfilename[49m[43m,[49m
[1;32m   2321[0m [43m            [49m[43mfacecolor[49m[38;5;241;43m=[39;49m[43mfacecolor[49m[43m,[49m
[1;32m   2322[0m [43m            [49m[43medgecolor[49m[38;5;241;43m=[39;49m[43medgecolor[49m[43m,[49m
[1;32m   2323[0m [43m            [49m[43morientation[49m[38;5;241;43m=[39;49m[43morientation[49m[43m,[49m
[1;32m   2324[0m [43m            [49m[43mbbox_inches_restore[49m[38;5;241;43m=[39;49m[43m_bbox_inches_restore[49m[43m,[49m
[1;32m   2325[0m [43m            [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   2326[0m [38;5;28;01mfinally[39;00m:
[1;32m   2327[0m     [38;5;28;01mif[39;00m bbox_inches [38;5;129;01mand[39;00m restore_bbox:

File [0;32m/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/matplotlib/backend_bases.py:1648[0m, in [0;36m_check_savefig_extra_args.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m   1640[0m     _api[38;5;241m.[39mwarn_deprecated(
[1;32m   1641[0m         [38;5;124m'[39m[38;5;124m3.3[39m[38;5;124m'[39m, name[38;5;241m=[39mname, removal[38;5;241m=[39m[38;5;124m'[39m[38;5;124m3.6[39m[38;5;124m'[39m,
[1;32m   1642[0m         message[38;5;241m=[39m[38;5;124m'[39m[38;5;132;01m%(name)s[39;00m[38;5;124m() got unexpected keyword argument [39m[38;5;124m"[39m[38;5;124m'[39m
[1;32m   1643[0m                 [38;5;241m+[39m arg [38;5;241m+[39m [38;5;124m'[39m[38;5;124m"[39m[38;5;124m which is no longer supported as of [39m[38;5;124m'[39m
[1;32m   1644[0m                 [38;5;124m'[39m[38;5;132;01m%(since)s[39;00m[38;5;124m and will become an error [39m[38;5;124m'[39m
[1;32m   1645[0m                 [38;5;124m'[39m[38;5;132;01m%(removal)s[39;00m[38;5;124m'[39m)
[1;32m   1646[0m     kwargs[38;5;241m.[39mpop(arg)
[0;32m-> 1648[0m [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/matplotlib/_api/deprecation.py:389[0m, in [0;36mdelete_parameter.<locals>.wrapper[0;34m(*inner_args, **inner_kwargs)[0m
[1;32m    384[0m [38;5;129m@functools[39m[38;5;241m.[39mwraps(func)
[1;32m    385[0m [38;5;28;01mdef[39;00m [38;5;21mwrapper[39m([38;5;241m*[39minner_args, [38;5;241m*[39m[38;5;241m*[39minner_kwargs):
[1;32m    386[0m     [38;5;28;01mif[39;00m [38;5;28mlen[39m(inner_args) [38;5;241m<[39m[38;5;241m=[39m name_idx [38;5;129;01mand[39;00m name [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m inner_kwargs:
[1;32m    387[0m         [38;5;66;03m# Early return in the simple, non-deprecated case (much faster than[39;00m
[1;32m    388[0m         [38;5;66;03m# calling bind()).[39;00m
[0;32m--> 389[0m         [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43minner_args[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43minner_kwargs[49m[43m)[49m
[1;32m    390[0m     arguments [38;5;241m=[39m signature[38;5;241m.[39mbind([38;5;241m*[39minner_args, [38;5;241m*[39m[38;5;241m*[39minner_kwargs)[38;5;241m.[39marguments
[1;32m    391[0m     [38;5;28;01mif[39;00m is_varargs [38;5;129;01mand[39;00m arguments[38;5;241m.[39mget(name):

File [0;32m/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py:2783[0m, in [0;36mFigureCanvasPdf.print_pdf[0;34m(self, filename, dpi, bbox_inches_restore, metadata)[0m
[1;32m   2781[0m     file [38;5;241m=[39m filename[38;5;241m.[39m_file
[1;32m   2782[0m [38;5;28;01melse[39;00m:
[0;32m-> 2783[0m     file [38;5;241m=[39m [43mPdfFile[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mmetadata[49m[38;5;241;43m=[39;49m[43mmetadata[49m[43m)[49m
[1;32m   2784[0m [38;5;28;01mtry[39;00m:
[1;32m   2785[0m     file[38;5;241m.[39mnewPage(width, height)

File [0;32m/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py:654[0m, in [0;36mPdfFile.__init__[0;34m(self, filename, metadata)[0m
[1;32m    652[0m [38;5;28mself[39m[38;5;241m.[39moriginal_file_like [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    653[0m [38;5;28mself[39m[38;5;241m.[39mtell_base [38;5;241m=[39m [38;5;241m0[39m
[0;32m--> 654[0m fh, opened [38;5;241m=[39m [43mcbook[49m[38;5;241;43m.[39;49m[43mto_filehandle[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mwb[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mreturn_opened[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m    655[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m opened:
[1;32m    656[0m     [38;5;28;01mtry[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/matplotlib/cbook/__init__.py:451[0m, in [0;36mto_filehandle[0;34m(fname, flag, return_opened, encoding)[0m
[1;32m    449[0m         fh [38;5;241m=[39m bz2[38;5;241m.[39mBZ2File(fname, flag)
[1;32m    450[0m     [38;5;28;01melse[39;00m:
[0;32m--> 451[0m         fh [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[43mflag[49m[43m,[49m[43m [49m[43mencoding[49m[38;5;241;43m=[39;49m[43mencoding[49m[43m)[49m
[1;32m    452[0m     opened [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    453[0m [38;5;28;01melif[39;00m [38;5;28mhasattr[39m(fname, [38;5;124m'[39m[38;5;124mseek[39m[38;5;124m'[39m):

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'figures/pmf_plot_poisson_mu20_bulk.pdf'
FileNotFoundError: [Errno 2] No such file or directory: 'figures/pmf_plot_poisson_mu20_bulk.pdf'

